# Hugo config.toml that controls variables for this website.
# For more info, see https://gohugo.io/getting-started/configuration/
# 
# Defaults:
#   Max chars per code line: 95
#

baseURL = "/"
title = "Ross Jacobs"
subtitle = "Subtitle appears under website title"
buildDrafts = false
enableGitInfo = true

# Current theme (multiple here to test their looks)
theme = "hugo-themes-learn"
# Options can be found here: https://help.farbox.com/pygments.html
PygmentsStyle = "monokai"

#disablePathToLower = False
languageCode = "en-US"
DefaultContentLanguage = "en"
postNavigation = true

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
disqusShortname = "Your disqus shortname"

# Setting a value will load highlight.js and enable syntax highlighting using the style selected.
# See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
# A preview of above styles can be viewed at https://highlightjs.org/static/demo/
hjsStyle = "default"

# Number of blog posts in each pagination page
paginatedsections = ["post"]
paginate = 6

[menu]
  # Commenting out while >_ svg links to /
  #[[menu.main]]
  #  identifier = "post"
  #  name = "blog"
  #  pre = "<i class='fas fa-newspaper'></i>"
  #  post = "<span class='alert'>New!</span>"
  #  url = "/post/"
  #  weight = 100
  [[menu.main]]
    identifier = "about"
    name = "about"
    pre = "<i class='fas fa-user-circle'></i>"
    url = "/about/"
    weight = 50
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects/"
    weight = 40
  [[menu.main]]
    identifier = "open_source"
    name = "open source"
    url = "/open_source/"
    weight = 20

[permalinks]
  post = "/post/:slug/"

[params]
  # If false, all contents of posts will appear on the front page and in pagination
  truncate = true
   
  # Org data
  orgName = "Ross Jacobs © 2019, all rights reserved"
  orgWebsite = "https://swit.sh"
  orgDescription = "Me, myself, and I"

  # Author's name (appears in meta tags and under posts)
  author = "Ross Jacobs"
  authorAvatar = "favicon.ico"
  authorLocation = "San Francisco, US" 
  authorWebsite = "https://swit.sh"
  authorDescription = "Herder of 1s and 0s"
  copyright = "© 2019 Ross Jacobs, all rights reserved."

  # cover image on front page
  #(source) cover = "http://q8iphone.me/wp-content/uploads/file-name-digital-background-5bd288a46a19b.png"
  cover = "https://dl.dropboxusercontent.com/s/wyk6n1bvrd02dpa/cover_image.webp"
  logo = "favicon.ico"

  # This text appears in site header under website title
  title = "Ross Jacobs"
  subtitle = "Herder of 1s and 0s"

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  #casper or caspertwo
  singleViewStyle = "casper"

  #twitterName = ""
  #fbName = ""
  githubName = "pocc"
  linkedinName = "rossbjacobs"
  emailName = "rj@swit.sh"

  # Text of the "Continue Reading" label. Supports markdown and inline HTML.
  # For example, &rarr; == right arrow.
  #continueReadingText = "Would you like to know more? &rarr;"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
  #googleAnalytics = "UA-XXXXX-X"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"

  # Switch to true to enable RSS icon link
  #rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  #textrss = false

  # Website's default description
  description = "Ross Jacobs' blog"

  # Populate with your search keywords - these will appear in meta tags
  # defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  #disableGoogleFonts = false

  # Remove or set to false to use local fonts
  #remoteFonts = false

  # Remove or set to false to use FontAwesome CDN, otherwise, the theme uses ForkAwesome local fonts.
  # fontAwesome = false

  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  showSupport = true

