baseURL = "https://tshark.dev/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Packet Analysis"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

pygmentsUseClasses = true
pygmentsCodeFences = true
enableRobotsTXT = true

[params]
  # Combined with current relative page, shows source page on Github
  editURL = "https://github.com/pocc/tshark.dev/blob/master/content/"
  description = "Capture Lifecycle"
  author = "Ross Jacobs"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  themeVariant = "blue"
  disableInlineCopyToClipBoard = "true"
  version = "v0.1"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
languageName = "English"
